print('Hello, What is your name?')
name = input()
print('Hello, ', name)
print('-----------------------')

# Operator: + - * /
num_1 = 45
num_2 = 4
print('num_1: ', num_1)
print('num_2: ', num_2)
print('num_1 + num_2 ', num_1 + num_2)
print('num_1 - num_2 ', num_1 - num_2)
print('num_1 * num_2 ', num_1 * num_2)
print('num_1 / num_2 ', num_1 / num_2)
print('num_1 ** num_2 ', num_1 ** num_2)
print('num_1 // num_2 ', num_1 // num_2)
print('num_1 % num_2 ', num_1 % num_2)
print('-----------------------')
num_1= input('Pick a number:')
num_2= input('Pick a number:')
print('num_1: ', num_1)
print('num_2: ', num_2)
print('type of num_1: ', num_1)
print('type of num_2: ', num_2)
print('Sum of num_1, num_2: ',int(num_1)+ int(num_2))
num_1=int(num_1)
num_2=int(num_2)
print('num_1 + num_2 ', num_1 + num_2)
print('num_1 - num_2 ', num_1 - num_2)
print('num_1 * num_2 ', num_1 * num_2)
print('num_1 / num_2 ', num_1 / num_2)
print('num_1 ** num_2 ', num_1 ** num_2)
print('num_1 // num_2 ', num_1 // num_2)
print('num_1 % num_2 ', num_1 % num_2)